import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen relative mx-auto`}>
        <Image
          className="opacity-[0.6] object-cover z-0 object-center md:object-top mx-auto"
          alt="Background image"
          src={"/media/background-image.svg"}
          fill={true}
          placeholder="blur"
          blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkqF9fDwADZAGv8BnBkgAAAABJRU5ErkJggg=="
        />
        {children}
      </body>
    </html>
  );
}
