import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppConfig } from "../../config";
import { emptyFunction } from "./lib/server.lib";
import ReactQueryProvider from "./provider";
import { AppBar } from "./components/AppBar";
import { BackgroundVideo } from "./components/BackgroundVideo";
import { AppConstants } from "./lib/constants.lib";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative mx-auto h-screen`}>
        <AppBar />
        <BackgroundVideo src={AppConstants.pages.home.background} />
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}

/**
 * Disable console.logs in production
 */
function disableConsoleLogs() {
  if (AppConfig().env === "production") {
    console.log === emptyFunction;
  }
}

disableConsoleLogs();
