import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import { AppConfig } from "../../config";
import { emptyFunction } from "./lib/server.lib";
import ReactQueryProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen relative mx-auto`}>
        <picture>
          <source
            srcSet="/media/desktop-background-image.svg"
            media="(min-width: 768px)"
          />
          <Image
            className="object-cover z-0 object-center md:object-bottom mx-auto opacity-80"
            alt="Background image"
            src={"/media/background-image.svg"}
            fill={true}
            placeholder="blur"
            blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkqF9fDwADZAGv8BnBkgAAAABJRU5ErkJggg=="
          />
        </picture>

        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}

/**
 * Disable console.logs in production
 */
function disableConsoleLogs() {
  if (AppConfig().env === "production") {
    console.log === emptyFunction;
  }
}

disableConsoleLogs();
